import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :demo, DemoWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  check_origin: [
    "https://journey-demo-prod-1074000674219.us-central1.run.app",
    "https://journey-demo-prod-6hrmbwesca-uc.a.run.app",
    "https://journey-demo-prod-1074000674219.us-west3.run.app",
    "https://journey-demo-prod-6hrmbwesca-wm.a.run.app",
    "https://demo.gojourney.dev",
    "//localhost"
  ]

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Demo.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
